#define	JEMALLOC_MACROLIST_C_
#include "jemalloc/internal/jemalloc_internal.h"

int macro_LG_RTREE_BITS_PER_LEVEL = LG_RTREE_BITS_PER_LEVEL;
int macro_LG_SIZEOF_PTR = LG_SIZEOF_PTR;
int macro_LG_PAGE = LG_PAGE;
int macro_CHUNK_MAP_RUNIND_SHIFT = CHUNK_MAP_RUNIND_SHIFT;
int macro_CHUNK_MAP_BININD_MASK = CHUNK_MAP_BININD_MASK;
int macro_CHUNK_MAP_BININD_SHIFT = CHUNK_MAP_BININD_SHIFT;
int macro_LG_BITMAP_GROUP_NBITS = LG_BITMAP_GROUP_NBITS;
int macro_BITMAP_GROUP_NBITS_MASK = BITMAP_GROUP_NBITS_MASK;
int macro_CHUNK_MAP_SIZE_SHIFT = CHUNK_MAP_SIZE_SHIFT;
int macro_NTBINS = NTBINS;
int macro_LG_SIZE_CLASS_GROUP = LG_SIZE_CLASS_GROUP;
int macro_LG_QUANTUM = LG_QUANTUM;
long macro_CHUNK_MAP_SIZE_MASK = CHUNK_MAP_SIZE_MASK;
//static int macro_LG_TINY_MAXCLASS = LG_TINY_MAXCLASS; 
